### ISSUE TITLE
ModuleNotFoundError: No module named 'util.cython.random_choice'

### ISSUE THREAD

**Issue by WEIFZH** [zyang1580/PDA#1]
Thanks for your work, while running the command, 
> python -u MF/simple_reproduce.py --dataset douban --epoch 2000 --save_flag 0 --log_interval 5 --start 0 --end 10 --step 1 --batch_size 2048 --lr 1e-2 --train s_condition --test s_condtion --saveID xxx --cuda 0 --regs 1e-2 --valid_set valid --pop_exp 0.22 --save_dir /home/PDA/save_model/ --Ks [20,50]

error occurs
> Traceback (most recent call last):
  File "MF/simple_reproduce.py", line 39, in <module>
    from evaluator import ProxyEvaluator
  File "/home/weifz/codes/PDA/evaluator/__init__.py", line 1, in <module>
    from .proxy_evaluator import ProxyEvaluator
  File "/home/weifz/codes/PDA/evaluator/proxy_evaluator.py", line 4, in <module>
    from util import typeassert
  File "/home/weifz/codes/PDA/util/__init__.py", line 14, in <module>
    from .cython.random_choice import batch_randint_choice
ModuleNotFoundError: No module named 'util.cython.random_choice'

could you tell me how to fix it, thanks a lot.

**Comment by zyang1580** [comment]
Has the package Cython been installed?

WEIFZH ***@***.***> 于2021年6月24日周四 上午11:51写道：

**Comment by WEIFZH** [comment]
No, but I noticed that there exists cython package in this repo, './util/cython' and the error occurs in './util/__init__.py'

**Comment by zyang1580** [comment]
You need to install it.  In init.py, it only tries to import something from
the package.

WEIFZH ***@***.***> 于2021年6月24日周四 下午8:54写道：

**Comment by WEIFZH** [comment]
Deleting this line of code works : )

**Comment by liangruiqian** [comment]
I also have a related problem.How did you solve this problem?
