### ISSUE TITLE
Kwai Datasets

### ISSUE THREAD

**Issue by Christopher7622** [zyang1580/PDA#12]
Hello,could you please provide me with a kwai Datasets?My e-mail is 1178752703@qq.com

**Comment by zyang1580** [comment]
I have sent it to you.

**Comment by lizhenstat** [comment]
Problem solved, the link is still valid.

**Comment by Christopher7622** [comment]
Thanks a lot，have a nice day！



发自我的iPhone


------------------ Original ------------------
From: Zhang Yang ***@***.***&gt;
Date: Tue,Aug 22,2023 9:04 PM
To: zyang1580/PDA ***@***.***&gt;
Cc: Christopher7622 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [zyang1580/PDA] Kwai Datasets (Issue #12)





 
I have sent it to you.
