### ISSUE TITLE
How is P(Z) calculated?

### ISSUE THREAD

**Issue by GXNU156489** [zyang1580/PDA#14]
hi

Thank you for sharing the code. I have a question. How did you calculate the P(Z) in the paper in the code?

Looking forward to your reply, thank you！

![image](https://github.com/zyang1580/PDA/assets/36919834/3cc69695-adb8-4721-8fb7-0609c7bdf1b2)

**Comment by zyang1580** [comment]
Kindly consult Section 2 of the paper.

**Comment by GXNU156489** [comment]
hi，Thank you for your reply. Can I understand E(Zγ) as local popularity?
![image](https://github.com/zyang1580/PDA/assets/36919834/3dfeeda6-4ac9-4dd6-8051-57e348aada4f)

**Comment by zyang1580** [comment]
No, the local popularity is used as follows:
![image](https://github.com/zyang1580/PDA/assets/52278611/f52e6737-22e6-4aa8-bb63-47723553aaa4)

**Comment by GXNU156489** [comment]
Thank you! I appreciate your help.
