### ISSUE TITLE
对激活函数的疑问

### ISSUE THREAD

**Issue by cizhouyu** [zyang1580/PDA#17]
您好，感谢您贡献的高质量论文和代码！
有一个问题想请教：
论文中使用到了 $ELU'$ 激活函数，没有过多解释使用该激活函数的原因；请问您在研究过程中有尝试过其他常用的激活函数比如说 
 $Sigmoid$ 激活函数吗，为什么最终采用了 $ELU'$ 作为激活函数呢，谢谢！

![image](https://github.com/zyang1580/PDA/assets/60316519/44f251d7-0916-4243-b867-e71ad63f5ff6)

**Comment by zyang1580** [comment]
感谢你的提问！

对于激活函数的主要考虑是保持输出的非负性，使得流行度对于不同的u-i匹配具有同性质的影响，如果激活函数的输出既有正，又有负，则流行度的影响可能是相反的，例如一个是放大，一个是缩小。

sigmoid的函数在我记忆中并没有尝试，记忆中应该是基于loss函数考虑没有尝试。此外，好像有个微信公众号文章，讲因果推荐实践，其中提到了对于激活函数进行了改动。

**Comment by cizhouyu** [comment]
谢谢您的回复！
