### ISSUE TITLE
README中对 t_0.txt 格式的描述有误

### ISSUE THREAD

**Issue by UnitDan** [zyang1580/PDA#3]
![image](https://user-images.githubusercontent.com/32333760/154445789-f56a63e6-6b72-4a98-af46-5e5ae79fcb64.png)
实际代码实现中是item interacted_user1 interacted_user2 ...

**Comment by zyang1580** [comment]
谢谢你指出这个问题，我将会确认并修改readme中的说明。

Liu Yuanhao ***@***.***> 于2022年2月17日周四 17:27写道：
