### ISSUE TITLE
Create_Recommendation & do recommendation function

### ISSUE THREAD

**Issue by Lucky168-1222** [zyang1580/PDA#8]
Excuse me, I would like to ask some questions about the 2 functions mentioned in the title：

- is there any difference between **Create_Recommendation** and **do recommendation** in the **DatasetApi_Model** class? 
- In the definition of the class init, is the **Create_Recommendation** function finally used to calculate the score during training? 
- I noticed that **do recommendation** was used to get top-k results during the test, but the calculated scores in the **do recommendation** function is the same as **Create_Recommendation**. And the test dataset in the class doesn't seem to work. Is there any connection between the two functions?

Looking forward to your reply！

**Comment by zyang1580** [comment]
``Create_Recommendation`` is used to create the computational graph, while ``do recommendation`` is used to run the corresponding operations.  For more details about creating computational graphs, please read the TensorFlow document.
